export const constantsProps = {
  APP_Name: 'ROSA Healthcare',
  numberFormatRegex: /^[0-9]*$/i,
  characterFormatRegex: /^[a-zA-Z\s]*$/,
  emailFormatRegex: /^[a-z0-9.]+@[a-z]+\.[a-z]{2,3}/,
  SERVER_CONNECTION_ERROR: 'The server encountered an unexpected condition.',
  UNKNOWN_ERROR: 'Unable to connect the server.',
  NOT_FOUND: 'The server could not find the requested resource.',
  ACCESS_DENIED: 'You don\'t have permission to access requested resource.',
  HOME: {
    ADDRESS: '123 ROSA, Delhi, India',
    PHONE: '(+097) 123 4567',
    EMAIL: 'Info@yourinfo.com'
  },
  BOOKING: {
    BOOKING_ADD_PAGE_NAME: 'Book Appointment',
    BTN_NAME: 'Book an appointment',
    USER_NAME: 'Full Name',
    USER_PHONE: 'Phone Number',
    APPOINTMENT_DATE: 'Date Of Appointment',
    APPOINTMENT_TIME: 'Time Of Appointment:',
    LAST_VISIT: 'Last Visit',
    DETAILS: 'Details'
  },
  USER_DETAILS: {
    USER_LIST_PAGE_NAME: 'Patients',
    USER_ADD_PAGE_NAME: 'Add Patient',
    USER_PRESCRIPTIONS: 'Prescriptions',
    USER_CHAT: 'Chat',
    USER_PASS: 'Password',
    USER_NAME: 'Name',
    USER_FIRST_NAME: 'First Name',
    USER_LAST_NAME: 'Last Name',
    USER_EMAIL: 'Mail-ID',
    USER_LOGIN_EMAIL: 'Email',
    USER_PASSWORD: 'Password',
    USER_MOBILE: 'Mobile',
    USER_BIRTH: 'Date Of Birth',
    USER_BIRTH_DATE: 'Birth Date',
    USER_BLOOD_GROUP: 'Blood Group',
    USER_TREATMENT: 'Treatment',
    USER_LOCATION: 'Location',
    USER_AGE: 'Age',
    USER_MARITAL_STATUS: 'Marital Status',
    USER_MARITAL_SINGLE: 'Single',
    USER_MARITAL_MARRIED: 'Married',
    USER_BLOOD_PRESURE: 'Blood Presure',
    USER_SUGGER: 'Sugger',
    GENDER: 'Gender',
    GENDER_FEMALE: 'Female',
    GENDER_MALE: 'Male',
    APPOINTMENT_DETAILS: 'Appointment Details',
    CONSULTING_DOC: 'Consulting Doctor',
    PENDING: 'Pending',
    VISITED: 'Visited',
    NOT_VISITED: 'Notvisited',
    USER_ADDRESS: 'Address',
    USER_CITY: 'City',
    USER_STATE: 'State',
    USER_PINCODE: 'Pincode',
    USER_STATUS: 'Status',
    USER_ACTIVE: 'Active',
    USER_INACTIVE: 'Inactive',
    USER_ACTION: 'Action',
    USER_ADD_BTN: 'Add New Patient',
    USER_UPDATE_BTN: 'Update Patient',
    STAFF_ADD_BTN: 'Add New Staff',
    STAFF_UPDATE_BTN: 'Update Staff'
  },
  MENUS: {
    LOGOUT: 'Logout',
    MENU: 'MENUS',
    LOGIN: 'Login',
  },
  NO_RECORDS: 'No Records Found.',
  BTN_SEARCH: {
    SEARCH: 'Search',
    RESET: 'Reset',
    CANCEL: 'Cancel',
    ACTION: 'Actions',
    SAVE: 'Save',
    SAVE_CHANGES: 'Save Changes'
  },
  DOCTOR_DETAILS: {
    DOCTOR_LIST_PAGE_NAME: 'Doctors',
    DOCTOR_ADD_PAGE_NAME: 'Add Doctor',
    DOCTOR_STAFF_LIST_PAGE_NAME: 'All Staffs',
    DOCTOR_STAFF_ADD_PAGE_NAME: 'Add Staffs',
    DOCTOR_SETTINGS: 'Settings',
    DOCTOR_FULL_NAME: 'Doctor Full Name',
    DOCTOR_NAME: 'Doctor Name',
    DOCTOR_DESCRIPTION: 'Profile Description',
    DOCTOR_EMAIL: 'Mail-ID',
    DOCTOR_PASS: 'Password',
    DOCTOR_REPASS: 'Re-Enter Password',
    DOCTOR_MOBILE: 'Mobile Number',
    DOCTOR_DESIGNATION: 'Designation',
    DOCTOR_SERVICE: 'Department',
    DOCTOR_AVAILABILITITY_STATUS: 'Availability Status',
    DOCTOR_AVAILABILITITY: 'Availability',
    DOCTOR_AVAILABLE: 'Available',
    DOCTOR_ABSEND: 'Absend',
    DOCTOR_AVAILABILITITY_TIME: 'Available Start and End Time',
    DOCTOR_TIME: 'TIme',
    DOCTOR_BIRTH: 'Birth Date',
    DOCTOR_EDUCATION: 'Education',
    DOCTOR_EXP: 'Experience (in Years)',
    DOCTOR_LOCATION: 'Location',
    DOCTOR_CITY: 'City',
    DOCTOR_STATE: 'State',
    DOCTOR_PINCODE: 'Pincode',
    DOCTOR_UP_PHOTO: 'Upload Photo',
    DOCTOR_IMG: 'Image',
    DOCTOR_DEG: 'Degree',
    DOCTOR_DESC: 'Service Description',
    DOCTOR_STATUS: 'Status',
    DOCTOR_ACTIVE: 'Active',
    DOCTOR_INACTIVE: 'Inactive',
    DOCTOR_ACTION: 'Action',
    DOCTOR_ADD_BTN: 'Add New Doctor',
    DOCTOR_UPDATE_BTN: 'Update Doctor'
  },
  BOOKED_APPOINTMENT_DETAILS: {
    VIEW_APPOINTMENTS_PAGE_NAME: 'View Appointments',
    BOOK_APPOINTMENTS_PAGE_NAME: 'Book Appointment',
    UPCOMING_APPOINTMENTS: 'Upcomming Appointments',
    PATIENT_NAME: 'Patient Name',
    PATIENT_EMAIL: 'Email',
    PATIENT_PHONE: 'Mobile',
    GENDER: 'Gender',
    ASSIGNED_DOCTOR: 'Doctor',
    DATE: 'Date',
    TIME: 'Time',
    DATETIME: 'Date & Time',
    DISEASES: 'Injury/Condition',
    STATUS: 'Status'
  }
}